apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webapp-rolebinding-16751
subjects:
  - kind: ServiceAccount
    name: webapp-sa-16751
roleRef:
  kind: Role
  name: webapp-role-16751
  apiGroup: rbac.authorization.k8s.io